[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit AHTX0
    adafruit/Adafruit BMP085 Library
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BusIO
    bblanchon/ArduinoJson
    Links2004/WebSockets